# Generated by Django 3.1.4 on 2022-10-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20221013_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prezioa',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
